# Generated by Django 4.1.1 on 2023-05-18 09:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trainings", "0003_rename_for_time_signup_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "training",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="trainings.training",
                    ),
                ),
                (
                    "cash_at_start",
                    models.SmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "cash_at_end",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("remarks", models.CharField(blank=True, default="", max_length=300)),
                (
                    "orga_1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_1",
                        to="trainings.signup",
                    ),
                ),
                (
                    "orga_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_2",
                        to="trainings.signup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=50)),
                (
                    "price",
                    models.SmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="bookkeeping.report",
                    ),
                ),
                (
                    "signup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="trainings.signup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=50)),
                (
                    "amount",
                    models.SmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="bookkeeping.report",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Absorption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.SmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "method",
                    models.SmallIntegerField(
                        choices=[(1, "Überweisung"), (2, "TWINT")]
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absorptions",
                        to="bookkeeping.report",
                    ),
                ),
                (
                    "signup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absorptions",
                        to="trainings.signup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.SmallIntegerField(
                        choices=[(1, "Flight"), (2, "Break"), (3, "Bus"), (4, "Boat")]
                    ),
                ),
                ("created_on", models.DateTimeField()),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="bookkeeping.report",
                    ),
                ),
                (
                    "signup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="trainings.signup",
                    ),
                ),
            ],
            options={
                "ordering": ("report", "created_on", "signup__pilot"),
                "unique_together": {("signup", "report", "created_on")},
            },
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prepaid_flights", models.SmallIntegerField()),
                (
                    "amount",
                    models.SmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "method",
                    models.SmallIntegerField(choices=[(0, "Bar"), (2, "TWINT")]),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="bookkeeping.report",
                    ),
                ),
                (
                    "signup",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bill",
                        to="trainings.signup",
                    ),
                ),
            ],
            options={
                "unique_together": {("signup", "report")},
            },
        ),
    ]
