# Generated by Django 4.1.1 on 2022-11-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookkeeping", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="cash_at_end",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
