# Generated by Django 4.1.1 on 2023-04-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookkeeping", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="absorption",
            name="method",
            field=models.SmallIntegerField(choices=[(1, "Überweisung"), (2, "TWINT")]),
        ),
        migrations.AlterField(
            model_name="bill",
            name="method",
            field=models.SmallIntegerField(choices=[(0, "Bar"), (2, "TWINT")]),
        ),
    ]
