# Generated by Django 4.1.1 on 2023-02-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookkeeping", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="method",
            field=models.SmallIntegerField(
                choices=[(0, "Bar"), (1, "TWINT")], default=0
            ),
        ),
    ]
