# Generated by Django 4.1.1 on 2022-12-21 12:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookkeeping", "0002_alter_report_cash_at_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="cash_at_end",
            field=models.SmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="cash_at_start",
            field=models.SmallIntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.SmallIntegerField(
                        choices=[(1, "Flight"), (2, "Bus"), (3, "Boat"), (4, "Break")]
                    ),
                ),
                ("created_on", models.DateTimeField()),
                (
                    "pilot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="bookkeeping.report",
                    ),
                ),
            ],
            options={
                "ordering": ("report", "created_on", "pilot"),
                "unique_together": {("pilot", "report", "created_on")},
            },
        ),
    ]
