# Generated by Django 4.1.1 on 2023-01-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookkeeping", "0002_alter_bill_payed_expense"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="remarks",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
    ]
