# Generated by Django 4.2.1 on 2024-05-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookkeeping", "0002_purchase_bookkeeping_descrip_50a862_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="kind",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Flight"),
                    (2, "Break"),
                    (3, "Bus"),
                    (4, "Boat"),
                    (5, "Flight With Postbus"),
                ]
            ),
        ),
    ]
