# Generated by Django 4.1.1 on 2023-04-25 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0001_initial"),
        ("bookkeeping", "0002_alter_absorption_method_alter_bill_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="orga_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports_1",
                to="trainings.signup",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="orga_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports_2",
                to="trainings.signup",
            ),
        ),
    ]
