# Generated by Django 4.2.1 on 2024-05-17 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookkeeping", "0003_alter_run_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="prepaid_flights",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="run",
            name="kind",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Flight"),
                    (2, "Break"),
                    (3, "Bus"),
                    (4, "Boat"),
                    (5, "Flight With Postbus"),
                    (6, "Flight With Lift"),
                ]
            ),
        ),
    ]
