# Generated by Django 4.1.1 on 2022-11-13 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_pilot_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_on",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
