# Generated by Django 4.1.1 on 2022-11-13 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_alter_post_created_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
