# Generated by Django 4.1.1 on 2022-12-24 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_alter_post_created_on"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pilot",
            options={"ordering": ["first_name", "last_name"]},
        ),
    ]
