# Generated by Django 4.1.1 on 2023-02-16 21:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_alter_pilot_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="pilot",
            name="prepaid_flights",
            field=models.SmallIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
