# Generated by Django 4.2.1 on 2023-10-05 18:30

from django.db import migrations, models


def mark_pilots_with_bills_not_new(apps, schema_editor):
    Pilot = apps.get_model("news", "Pilot")
    for pilot in Pilot.objects.all():
        if any(hasattr(signup, "bill") for signup in pilot.signups.all()):
            pilot.is_new = False
            pilot.save()


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_pilot_prepaid_flights"),
    ]

    operations = [
        migrations.AddField(
            model_name="pilot",
            name="is_new",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(mark_pilots_with_bills_not_new),
    ]
