# Generated by Django 4.2.1 on 2024-05-17 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0007_pilot_is_new"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pilot",
            name="prepaid_flights",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
