# Generated by Django 4.0.4 on 2022-06-26 13:12

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('max_pilots', models.PositiveSmallIntegerField(default=11, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(21)])),
                ('priority_date', models.DateField(default=datetime.date(2010, 4, 9))),
                ('info', models.CharField(blank=True, default='', max_length=300)),
                ('emergency_mail_sender', models.ForeignKey(blank=True, db_index=False, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'Selected'), (2, 'Waiting'), (3, 'Canceled')], default=2)),
                ('signed_up_on', models.DateTimeField(auto_now_add=True)),
                ('is_certain', models.BooleanField(default=True)),
                ('for_time', models.SmallIntegerField(choices=[(1, 'Wholeday'), (2, 'Arrivelate'), (3, 'Leaveearly'), (4, 'Individually')], default=1)),
                ('for_sketchy_weather', models.BooleanField(default=True)),
                ('comment', models.CharField(blank=True, default='', max_length=150)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to=settings.AUTH_USER_MODEL)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='trainings.training')),
            ],
            options={
                'ordering': ['status', 'signed_up_on'],
                'unique_together': {('pilot', 'training')},
            },
        ),
    ]
