# Generated by Django 3.2.12 on 2022-04-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['date', 'pilot']},
        ),
        migrations.AddField(
            model_name='registration',
            name='comment',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
