# Generated by Django 4.0.4 on 2022-06-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='for_time',
            field=models.SmallIntegerField(choices=[(1, 'Wholeday'), (2, 'Arrivelate'), (3, 'Leaveearly'), (4, 'Individually')], default=1),
        ),
        migrations.AlterField(
            model_name='signup',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Selected'), (2, 'Waiting'), (3, 'Canceled')], default=2),
        ),
    ]
