# Generated by Django 4.0.4 on 2022-04-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singup',
            options={'ordering': ['status', 'created_on']},
        ),
        migrations.AlterField(
            model_name='singup',
            name='status',
            field=models.IntegerField(choices=[(1, 'Selected'), (2, 'Waiting'), (3, 'Canceled')], default=2),
        ),
    ]
