# Generated by Django 4.1.1 on 2023-04-29 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0002_alter_signup_for_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="signup",
            old_name="for_time",
            new_name="duration",
        ),
    ]
