# Generated by Django 4.0.4 on 2022-06-07 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_signup_for_time_alter_signup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='priority_date',
            field=models.DateField(default=datetime.date(2010, 4, 9)),
        ),
    ]
