# Generated by Django 3.2.12 on 2022-04-16 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_alter_registration_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='comment',
        ),
    ]
