# Generated by Django 4.0.4 on 2022-06-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_training_emergency_mail_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='certainty',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
