# Generated by Django 3.2.12 on 2022-04-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_alter_registration_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('🟡', 'Wait'), ('🟢', 'Selected'), ('❌', 'Canceled')], default='🟡', max_length=4),
        ),
    ]
