# Generated by Django 4.2.1 on 2023-09-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0003_rename_for_time_signup_duration"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="signup",
            index=models.Index(fields=["status"], name="trainings_s_status_c94ee7_idx"),
        ),
        migrations.AddIndex(
            model_name="training",
            index=models.Index(fields=["date"], name="trainings_t_date_81aa6e_idx"),
        ),
    ]
