# Generated by Django 3.2.12 on 2022-04-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_remove_registration_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
