# Generated by Django 4.0.4 on 2022-06-05 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_signup_certainty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='certainty',
        ),
        migrations.AddField(
            model_name='signup',
            name='is_certaint',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='max_pilots',
            field=models.PositiveSmallIntegerField(default=11, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(21)]),
        ),
    ]
