# Generated by Django 5.2.1 on 2025-06-08 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_signup_trainings_s_status_c94ee7_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='max_pilots',
            field=models.PositiveSmallIntegerField(default=11, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(33)]),
        ),
    ]
