# Generated by Django 4.0.4 on 2022-06-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0005_remove_signup_certainty_signup_is_certaint_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='is_certaint',
            new_name='is_certain',
        ),
    ]
